itake/inventory/website/itake/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .import views

app_name = 'itake'

urlpatterns = [
    #url for homepage
    url(r'^$',views.index,name="index"),
    #url for login
    url(r'^login/$', views.login1, name = "login"),

    #url for product pages
    url(r'^product/$',views.productList.as_view(),name="productList"),
    url(r'^product/add/$', views.productCreate.as_view(), name = "productCreate"),
    url(r'^product/update/(?P<product_id>[0-9]+)/$', views.productUpdate, name="productUpdate"),
    url(r'^product/(?P<product_id>[0-9]+)/$',views.productDetails, name="productDetails"),
    url(r'^product/delete/(?P<product_id>[0-9]+)/$', views.productDelete, name = "productDelete"),

    #url for vendor pages
    url(r'^vendor/$',views.vendorList.as_view(),name="vendorList"),
    url(r'^vendor/(?P<vendor_id>[0-9]+)/$',views.vendorDetails, name="vendorDetails"),
    url(r'^vendor/add/$', views.vendorCreate.as_view(), name="vendorCreate"),

    #url for order pages
    url(r'^order/$',views.orderList.as_view(),name="orderList"),
    url(r'^order/(?P<order_id>[0-9]+)/$',views.orderDetails, name="orderDetails"),
    url(r'^order/add/$', views.orderCreate.as_view(), name = "orderCreate"),

]

urlpatterns += staticfiles_urlpatterns()

itake/inventory/website/website/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^itake/', include('itake.urls')),
]

itake/inventory/website/itake/models.py
from django.db import models
from datetime import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from django.contrib import admin

# Create your models here.


class Vendor(models.Model):
    vendorName = models.CharField(max_length=500)
    vendorPhone = models.CharField(max_length=500, null=True)
    vendorEmail = models.CharField(max_length=500, null=True)
    vendorID = models.CharField(max_length=100,blank=True, null=True)
    def __str__(self):
        return self.vendorName
# when the new product is added, it should be displayed in the detail /list pate?
    def get_absolute_url(self):
        return reverse('itake:vendorList')



class Warehouse(models.Model):
    warehouseID = models.IntegerField(primary_key=True)
    warehouseName = models.CharField(max_length=100,blank=True, null=True)
    warehouseAddress = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.warehouseName



class Product(models.Model):
    productName =  models.CharField(max_length=500)
    category = models.CharField(max_length=250)
    description = models.CharField(max_length=1000)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    maxProduct = models.IntegerField(default=30)
    autoRequest = models.BooleanField()
    thresholdLevel = models.IntegerField(default=30)
    quantity = models.IntegerField(default=20)
    productID = models.CharField(max_length=100, blank=True, null=True)
    vendor = models.ForeignKey(Vendor,on_delete=models.CASCADE,null=True,related_name='vendor')
    warehouse = models.ManyToManyField(Warehouse,related_name="pro_ware", through="ProductWarehouse")
    def __str__(self):
        return self.productName + "-" + self.category
#when the new product is added, it should be displayed in the detail /list pate?
    def get_absolute_url(self):
        return reverse('itake:productList')

class ProductWarehouse(models.Model):
    warehouse=models.ForeignKey(Warehouse,on_delete=models.CASCADE,null=True, related_name='warehouse')
    product=models.ForeignKey(Product, on_delete=models.CASCADE,null=True, related_name='warepro')
    quantity = models.IntegerField(default=20)
    def __str__(self):
        return self.product.productName + '-' +self.warehouse.warehouseName


class Order(models.Model):
    orderID = models.CharField(max_length=100, blank=True, null=True)
    products = models.ManyToManyField(Product,related_name="order_item", through="OrderItem")
    requestedDate = models.DateField(default=datetime.now, blank=True, null=True)
    receivedDate = models.DateField(default=datetime.now, blank=True, null=True)
    orderStatus = models.CharField(max_length=100,blank=True, null=True)
    #sumPrice = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    #receivedDate = models.CharField(max_length=100,blank=True, null=True)


    def __str__(self):
        return self.orderID


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,null=True, related_name='product')
    #cost = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    order = models.ForeignKey(Order,on_delete=models.CASCADE, null=True,related_name='items')
    orderQuantity = models.IntegerField(default=10)
    #orderItemID = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.order.orderID + '-' +self.product.productName




#admin models
class OrderAdmin(admin.ModelAdmin):
    class OrderItemInline(admin.TabularInline):
        model = OrderItem
    inlines = [OrderItemInline,]

class ProWareAdmin(admin.ModelAdmin):
    class ProWareInline(admin.TabularInline):
        model = ProductWarehouse
    inlines = [ProWareInline,]

itake/inventory/website/itake/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from django.template import loader
from django.shortcuts import render, get_object_or_404,redirect
from django.views import generic
from django.forms import ModelForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.
def index(request):
        # creating a dictionary:
        template = loader.get_template('itake/index.html')
        return render(request,'itake/index.html')

#def productList(request):
        #all_product = Product.objects.all()
        #context = {'all_product':all_product}
        #return render(request,'itake/product.html',context)






#use class to create view

#class for product

class productForm(ModelForm):
        class Meta:
                model = Product
                fields = ['productName', 'category', 'description', 'price', 'maxProduct', 'autoRequest',
                  'thresholdLevel', 'quantity', 'productID', 'vendor', 'warehouse']

#view for productList page
class productList(generic.ListView):
        template_name = 'itake/product.html'
        context_object_name = 'all_product'
        def get_queryset(self):
                return Product.objects.all()

#view for productForm page (add products)
class productCreate(CreateView):
        model = Product
        fields = ['productName','category','description','price','maxProduct','autoRequest',
                  'thresholdLevel','quantity','productID','vendor','warehouse']

#update view
def productUpdate(request, product_id, template_name='itake/product_form.html'):
    product=get_object_or_404(Product,pk=product_id)
    form=productForm(request.POST or None, instance=product)
    ctx = {"form": form, "product": product}
    if form.is_valid():
        form.save()
        return redirect('itake:productList')
    return render(request,template_name,ctx)

#view for product detail page
def productDetails(request, product_id):
        product= get_object_or_404(Product,pk=product_id)
        context = {'product': product}
        return render(request, 'itake/productDetails.html', context)

#view for product delete
def productDelete(request, product_id, template_name='itake/productDeleteConfirm.html'):
    product= get_object_or_404(Product, pk=product_id)
    if request.method=='POST':
        product.delete()
        return redirect('itake:productList')
    ctx = {"product": product}
    return render(request, template_name, ctx)


#========================for vendor=======================================

# view for vendorList page
class vendorList(generic.ListView):
        template_name = 'itake/vendor.html'
        context_object_name = 'all_vendor'

        def get_queryset(self):
                return Vendor.objects.all()

#view for vendorDetails page
def vendorDetails(request, vendor_id):
        vendor = get_object_or_404(Vendor,pk=vendor_id)
        product=vendor.vendor.all()
        context = {'vendor': vendor,'product':product}
        return render(request, 'itake/vendorDetails.html', context)

#view for vendorForm page (add products)
class vendorCreate(CreateView):
        model = Vendor
        fields = ['vendorName','vendorPhone']

#===================================for order=================================

class orderList(generic.ListView):
    template_name = 'itake/order.html'
    context_object_name = 'all_order'

    def get_queryset(self):
        return Order.objects.all()

#view for orderDetails page
def orderDetails(request,order_id):
        order = get_object_or_404(Order,pk=order_id)
        orderitem = order.items.all()
        context = {'order': order,'orderitem':orderitem}
        return render(request, 'itake/orderDetails.html', context)

#view for order page

class orderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['orderID', 'products', 'requestedDate', 'receivedDate', 'orderStatus']



class orderCreate(CreateView):
        model = Order
        fields = ['orderID','products','requestedDate','receivedDate','orderStatus']



class orderItemForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['order','product','orderQuantity']

#===========================================view for login page===============================

def login1(request):
    if 'register' in request.POST:
        username = request.POST['username']
        password = request.POST['password']
        first_name = request.POST['fname']
        last_name = request.POST['lname']
        user = User.objects.create_user(username=username, password=password, first_name=first_name, last_name = last_name)
        user.save()
        return render(request, 'itake/Login_page.html')
    elif 'login-form' in request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)
        if user is not None:
            login(request, user)
            #return render(request, 'login/thankyou.html')
            return render(request, 'itake/index.html')
        else:
            return render(request, 'itake/Login_page.html')
    else:
        return render(request, 'itake/Login_page.html')



itake/inventory/website/itake/templates/itake/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>InventorySystem</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="collapse navbar-collapse row" id="navigation">
        <div class="container">
            <div class="col-lg-12">
            <ul class="nav navbar-nav navbar-right">
            <li><a data-toggle="bar" href="{% url 'itake:index' %}">Home Page</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:productList' %}">Product</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:vendorList' %}">Vendor</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:orderList' %}">Order</a></li>
                <li><a data-toggle="bar" href="{% url 'itake:login' %}">Login</a></li>
            </ul>
            </div>
        </div>
    </div>
</nav>



<div class="row">
<br><br><br>
</div>

<div class="container">

    <div class="row">


            <div class="col-lg-11">
                <h1 class="page-header">Welcome to the iTake Inventory Management System</h1>
                <p class="text-justify">iTake system saves any distribution countless hours of work associated
                    with data entry, organization and fulfillment. You'll be able to convert
                    leads to orders, orders to shipments, and shipments to revenue in short order.</p>
                <br><br>
            </div>


    </div>

</div>







    <div class="container">

        <div class="row">


            <div class="col-md-3">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h5>
                            Product Management
                        </h5>
                    </div>
                    <div class="panel-body">
                        <p>This section is for product management.
                            You can add, edit and delete products in this part.
                        </p>
                        <br><br>
                        <a class="btn btn-default" href="{% url 'itake:productList' %}">Product</a>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h5>
                            Vendor Management
                        </h5>
                    </div>
                    <div class="panel-body">
                        <p>This section is for vendor management.
                            You can add, edit and delete vendors in this part.
                        </p>
                        <br><br>
                        <a class="btn btn-default" href="{% url 'itake:vendorList' %}">Vendor</a>
                    </div>
                </div>
            </div>


            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5>
                            Order Management
                        </h5>
                    </div>
                    <div class="panel-body">
                        <p>This section is for vendor management.
                            You can place and update orders in this part.
                        </p>
                        <br><br>
                        <a class="btn btn-default" href="{% url 'itake:orderList' %}">Order</a>
                    </div>
                </div>
            </div>

        </div>

    </div>

</body>
</html>

itake/inventory/website/itake/templates/itake/order.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="collapse navbar-collapse row" id="navigation">
        <div class="container">
            <div class="col-lg-12">
            <ul class="nav navbar-nav navbar-right">
            <li><a data-toggle="bar" href="{% url 'itake:index' %}">Home Page</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:productList' %}">Product</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:vendorList' %}">Vendor</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:orderList' %}">Order</a></li>
                 <li><a data-toggle="bar" href="{% url 'itake:login' %}">Login</a></li>
            </ul>
            </div>
        </div>
    </div>
</nav>

<div class="row">
<br><br><br>
</div>
<div class="container">

    <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Order List</h2>
                <br>
            </div>
    </div>

    <! -- for product table -->
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Order ID</th>

                </tr>
                </thead>
                <tbody>
                {% for order in all_order %}
                <tr>
                    <td>
                        <a href="{% url 'itake:orderDetails' order.id %}"> {{ order.orderID}} </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>



        </div>
    </div>

</div>

</body>
</html>

itake/inventory/website/itake/templates/itake/orderDetails.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>orderDtails</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="collapse navbar-collapse row" id="navigation">
        <div class="container">
            <div class="col-lg-12">
            <ul class="nav navbar-nav navbar-right">
            <li><a data-toggle="bar" href="{% url 'itake:index' %}">Home Page</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:productList' %}">Product</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:vendorList' %}">Vendor</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:orderList' %}">Order</a></li>
                 <li><a data-toggle="bar" href="{% url 'itake:login' %}">Login</a></li>
            </ul>
            </div>
        </div>
    </div>
</nav>

<div class="row">
<br><br><br>
</div>

<div class="container">

    <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">
                    Order: {{order.orderID}}
                </h2>
                <br>
            </div>
    </div>



    <div class="row">
        <div class="col-lg-8">
            <h4>Order Details</h4>

                <p>OrderID: {{order.orderID}}</p>
                <p>Products:</p>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Product Price</th>
                    <th>Product Quantiy</th>
                </tr>
                </thead>
                <tbody>

                {% for orderitem in orderitem %}
                <tr>
                    <td>
                         {{ orderitem.product.productName}}
                    </td>
                    <td>
                        {{orderitem.product.price}}
                    </td>
                    <td>
                        {{orderitem.orderQuantity}}
                    </td>
                </tr>

                {% endfor %}
                </tbody>
            </table>














        </div>
    </div>

</div>
</body>
</html>

itake/inventory/website/itake/templates/itake/order_form.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>orderForm</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="collapse navbar-collapse row" id="navigation">
        <div class="container">
            <div class="col-lg-12">
            <ul class="nav navbar-nav navbar-right">
            <li><a data-toggle="bar" href="{% url 'itake:index' %}">Home Page</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:productList' %}">Product</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:vendorList' %}">Vendor</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:orderList' %}">Order</a></li>
                 <li><a data-toggle="bar" href="{% url 'itake:login' %}">Login</a></li>
            </ul>
            </div>
        </div>
    </div>
</nav>

<div class="row">
<br><br><br>
</div>

<div class="container">


    <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Order Details</h2>
                <br>
            </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
        <form action="" method="post" class="form-inline" role="form">
            {% csrf_token %}
            {% for field in form %}
            <label> {{field.label_tag}}</label>
            <br>
            {{field}}
            <br><br>
            {% endfor %}
            <br>
            <button class="btn btn-default" type="submit">Submit</button>
        </form>
        </div>
    </div>

    <br><br>


</div>

</body>
</html>

itake/inventory/website/itake/templates/itake/product.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ProductList</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="collapse navbar-collapse row" id="navigation">
        <div class="container">
            <div class="col-lg-12">
            <ul class="nav navbar-nav navbar-right">
            <li><a data-toggle="bar" href="{% url 'itake:index' %}">Home Page</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:productList' %}">Product</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:vendorList' %}">Vendor</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:orderList' %}">Order</a></li>
                 <li><a data-toggle="bar" href="{% url 'itake:login' %}">Login</a></li>
            </ul>
            </div>
        </div>
    </div>
</nav>

<div class="row">
<br><br><br>
</div>

<div class="container">

    <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Product List</h2>
                <br>
            </div>
    </div>

    <! -- for product table -->
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Category</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for product in all_product %}
                <tr>
                    <td>
                        <a href="{% url 'itake:productDetails' product.id %}"> {{ product.productName}} </a>
                    </td>
                    <td>{{product.category}}</td>
                    <td>
                        <a href="{% url 'itake:productUpdate' product.id %}">Edit</a>
                    </td>
                    <td>
                        <a href="{% url 'itake:productDelete' product.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>


            <a class="btn btn-default" href="{% url 'itake:productCreate' %}">Add Product</a>

        </div>
    </div>

</div>






</body>

</html>

itake/inventory/website/itake/templates/itake/productDeleteConfirm.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ProductDeleteConfirm</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="collapse navbar-collapse row" id="navigation">
        <div class="container">
            <div class="col-lg-12">
            <ul class="nav navbar-nav navbar-right">
            <li><a data-toggle="bar" href="{% url 'itake:index' %}">Home Page</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:productList' %}">Product</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:vendorList' %}">Vendor</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:orderList' %}">Order</a></li>
                 <li><a data-toggle="bar" href="{% url 'itake:login' %}">Login</a></li>
            </ul>
            </div>
        </div>
    </div>
</nav>

<div class="row">
<br><br><br>
</div>

<div class="container">


    <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Product Information</h2>
                <br>
            </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
        <form method="post">
        {% csrf_token %}
        Are you sure you want to delete "{{ product.productName }}" ?
        <br>
        <button class="btn btn-default" type="submit">Submit</button>
        </form>
        </div>
    </div>
</div>

</body>
</html>

itake/inventory/website/itake/templates/itake/productDetails.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>productDetails</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="collapse navbar-collapse row" id="navigation">
        <div class="container">
            <div class="col-lg-12">
            <ul class="nav navbar-nav navbar-right">
            <li><a data-toggle="bar" href="{% url 'itake:index' %}">Home Page</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:productList' %}">Product</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:vendorList' %}">Vendor</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:orderList' %}">Order</a></li>
                 <li><a data-toggle="bar" href="{% url 'itake:login' %}">Login</a></li>
            </ul>
            </div>
        </div>
    </div>
</nav>

<div class="row">
<br><br><br>
</div>

<div class="container">

    <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">
                    {{product.productName}}
                </h2>
                <br>
            </div>
    </div>

    <div class="row">
        <div class="col-lg-8">
            <h4>Product Details</h4>
            <ul>
                <li>Product Category: {{product.category}}</li>
                <li>Product Description: {{product.description}}</li>
                <li>Product Cost: {{product.cost}}</li>
                <li>Product Vendor: {{product.vendor}}</li>
            </ul>
                     <a class="btn btn-default" href="{% url 'itake:productUpdate' product.id%}">Update Product</a>
        </div>
    </div>

</div>
</body>
</html>

itake/inventory/website/itake/templates/itake/vendor.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>VendorList</title>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="collapse navbar-collapse row" id="navigation">
        <div class="container">
            <div class="col-lg-12">
            <ul class="nav navbar-nav navbar-right">
            <li><a data-toggle="bar" href="{% url 'itake:index' %}">Home Page</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:productList' %}">Product</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:vendorList' %}">Vendor</a></li>
            <li><a data-toggle="bar" href="{% url 'itake:orderList' %}">Order</a></li>
                 <li><a data-toggle="bar" href="{% url 'itake:login' %}">Login</a></li>
            </ul>
            </div>
        </div>
    </div>
</nav>

<div class="row">
<br><br><br>
</div>

<div class="container">

    <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Vendor List</h2>
                <br>
            </div>
    </div>

    <! -- for product table -->
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Vendor Name</th>
                    <th>Vendor Email</th>
                </tr>
                </thead>
                <tbody>
                {% for vendor in all_vendor %}
                <tr>
                    <td>
                        <a href="{% url 'itake:vendorDetails' vendor.id %}"> {{ vendor.vendorName}} </a>
                    </td>
                    <td>
                        {{vendor.vendorEmail}}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>


            <a class="btn btn-default" href="{% url 'itake:vendorCreate' %}">Add Vendor</a>

        </div>
    </div>

</div>


</body>
</html>